### ISSUE TITLE
Posting PR comment fails the action when the generated plan is large

### ISSUE THREAD

**Issue by glenthomas** [dflook/terraform-github-actions#197]
### Problem description

I have a Terraform module that is generating a large plan output. When the action attempts to post the plan comment to the pull request, GitHub responds with an HTTP error because the comment is too large (maximum 65536 characters).

I am able to work around this by setting `add_github_comment: "false"` but it would be great if the action could gracefully handle the error and maybe post a comment that says "the plan is too large to post as a comment but can be viewed from the workflow log".

### Terraform version

1.2.4

### Backend

s3

### Workflow YAML

```yaml
- name: Terraform Plan
      uses: dflook/terraform-plan@4760c89110711b8024fd3e059db0b37313dd9bd0
      id: plan
      with:
        path: ${{ inputs.path }}
        label: ${{ inputs.label }}
        backend_config_file: ${{ inputs.backend_config_file }}
        var_file: ${{ inputs.var_file }}
        add_github_comment: ${{ inputs.add_github_comment }}
```

### Workflow log

```shell
Validation Failed
##[debug]{'Server': 'GitHub.com', 'Date': 'Wed, 06 Jul 2022 09:04:43 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '252', 'X-GitHub-Media-Type': 'github.v3; format=json', 'X-RateLimit-Limit': '15000', 'X-RateLimit-Remaining': '14980', 'X-RateLimit-Reset': '1657100406', 'X-RateLimit-Used': '20', 'X-RateLimit-Resource': 'core', 'Access-Control-Expose-Headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset', 'Access-Control-Allow-Origin': '*', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'X-Frame-Options': 'deny', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '0', 'Referrer-Policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'Content-Security-Policy': "default-src 'none'", 'Vary': 'Accept-Encoding, Accept, X-Requested-With', 'X-GitHub-Request-Id': '07C0:5099:3187F12:9052604:62C2202B'}
##[debug]{"message":"Validation Failed","errors":[{"resource":"IssueComment","code":"custom","field":"body","message":"body is too long (maximum is 65536 characters)"}],"documentation_url":"https://docs.github.com/rest/reference/issues#update-an-issue-comment"}
Traceback (most recent call last):
  File "/usr/local/bin/github_pr_comment", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/github_pr_comment/__main__.py", line 260, in main
    comment = update_comment(
  File "/usr/local/lib/python3.9/dist-packages/github_pr_comment/comment.py", line 302, in update_comment
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/my-org/my-repo/issues/comments/2369701789
```

**Comment by glenthomas** [comment]
Probably a duplicate of #133

**Comment by dflook** [comment]
Hi @glenthomas, large plans are now supported in v1.27.0
