### ISSUE TITLE
Create new workspace stopped working without any changes

### ISSUE THREAD

**Issue by jstuessy** [dflook/terraform-github-actions#261]
### Problem description

We have our action setup to create preview builds when needed. Everything was working fine until yesterday afternoon when it suddenly stopped working with the following errors

 Traceback (most recent call last):
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 126, in feed_token
      action, arg = states[state][token.type]
  KeyError: 'STRING_LIT'

     raise UnexpectedToken(token, expected, state=self, interactive_parser=None)
  lark.exceptions.UnexpectedToken: Unexpected token Token('STRING_LIT', '",\n        awslogs-region        = "') at line 244, column 72.

  Terraform has been successfully initialized!
Error: Failed to list workspaces

### Workflow YAML

```yaml
jobs:
  build:
    if: ${{ github.event.label.name == 'Preview' || contains(github.event.pull_request.labels.*.name, 'Preview') }}
    runs-on: ubuntu-latest
    outputs:
      deployment: ${{ steps.deployment.outputs.deployment_id }}
      build_name: ${{ steps.tf-outputs.outputs.build_name}}
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
    - name: Set AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Find or create workspace
      uses: dflook/terraform-new-workspace@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        path: terraform/staging/
        workspace: ${{github.event.pull_request.number}}
```

### Workflow log

```shell
Run dflook/terraform-new-workspace@v1
/usr/bin/docker run --name danielflookterraformgithubactionssha2561a65b03b960c8737dce51e74faf1482322bffc6fba5177288489f101086f9c75_38afd7 --label 6c0442 --workdir /github/workspace --rm -e "AWS_DEFAULT_REGION" -e "AWS_REGION" -e "AWS_ACCESS_KEY_ID" -e "AWS_SECRET_ACCESS_KEY" -e "INPUT_PATH" -e "INPUT_WORKSPACE" -e "INPUT_BACKEND_CONFIG" -e "INPUT_BACKEND_CONFIG_FILE" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true --entrypoint "/entrypoints/new-workspace.sh" -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/edge/edge":"/github/workspace" danielflook/terraform-github-actions@sha256:1a65b03b960c8737dce51e74faf1482322bffc6fba5177288489f101086f9c75
Installing Terraform
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 126, in feed_token
      action, arg = states[state][token.type]
  KeyError: 'STRING_LIT'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/dist-packages/terraform/hcl.py", line 16, in try_load
      return hcl2.load(f)
    File "/usr/local/lib/python3.9/dist-packages/hcl2/api.py", line 14, in load
      return loads(file.read(), with_meta=with_meta)
    File "/usr/local/lib/python3.9/dist-packages/hcl2/api.py", line 27, in loads
      tree = hcl2.parse(text + "\n")
    File "/usr/local/lib/python3.9/dist-packages/lark/lark.py", line 645, in parse
      return self.parser.parse(text, start=start, on_error=on_error)
    File "/usr/local/lib/python3.9/dist-packages/lark/parser_frontends.py", line 96, in parse
      return self.parser.parse(stream, chosen_start, **kw)
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 41, in parse
      return self.parser.parse(lexer, start)
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 171, in parse
      return self.parse_from_state(parser_state)
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 193, in parse_from_state
      raise e
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 184, in parse_from_state
      state.feed_token(token)
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 129, in feed_token
      raise UnexpectedToken(token, expected, state=self, interactive_parser=None)
  lark.exceptions.UnexpectedToken: Unexpected token Token('STRING_LIT', '",\n        awslogs-region        = "') at line 244, column 72.
  Expected one of: 
  	* QMARK
  	* __ANON_7
  	* RBRACE
  	* COMMA
  	* STAR
  	* __ANON_5
  	* PERCENT
  	* SLASH
  	* __ANON_9
  	* __ANON_4
  	* __ANON_0
  	* MORETHAN
  	* PLUS
  	* __ANON_1
  	* LSQB
  	* __ANON_6
  	* DOT
  	* MINUS
  	* __ANON_14
  	* __ANON_13
  	* LESSTHAN
  	* __ANON_8
  	* __ANON_2
  
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.9/dist-packages/terraform/hcl.py", line 61, in <module>
      try_load(Path(sys.argv[1]))
    File "/usr/local/lib/python3.9/dist-packages/terraform/hcl.py", line 18, in try_load
      debug(e)
    File "/usr/local/lib/python3.9/dist-packages/github_actions/debug.py", line 9, in debug
      for line in msg.splitlines():
  AttributeError: 'UnexpectedToken' object has no attribute 'splitlines'
  gpg: Signature made Wed Apr 26 18:13:42 2023 UTC
  gpg:                using RSA key 374EC75B485913604A831CC7C820C6D5CD27AB87
  gpg: Good signature from "HashiCorp Security (hashicorp.com/security) <security@hashicorp.com>" [ultimate]
  terraform_1.4.6_linux_amd64.zip: OK
  Using latest terraform version that matches the required_version constraints
  Switched to Terraform v1.4.6
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 126, in feed_token
      action, arg = states[state][token.type]
  KeyError: 'STRING_LIT'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/dist-packages/terraform/hcl.py", line 16, in try_load
      return hcl2.load(f)
    File "/usr/local/lib/python3.9/dist-packages/hcl2/api.py", line 14, in load
      return loads(file.read(), with_meta=with_meta)
    File "/usr/local/lib/python3.9/dist-packages/hcl2/api.py", line 27, in loads
      tree = hcl2.parse(text + "\n")
    File "/usr/local/lib/python3.9/dist-packages/lark/lark.py", line 645, in parse
      return self.parser.parse(text, start=start, on_error=on_error)
    File "/usr/local/lib/python3.9/dist-packages/lark/parser_frontends.py", line 96, in parse
      return self.parser.parse(stream, chosen_start, **kw)
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 41, in parse
      return self.parser.parse(lexer, start)
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 171, in parse
      return self.parse_from_state(parser_state)
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 193, in parse_from_state
      raise e
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 184, in parse_from_state
      state.feed_token(token)
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 129, in feed_token
      raise UnexpectedToken(token, expected, state=self, interactive_parser=None)
  lark.exceptions.UnexpectedToken: Unexpected token Token('STRING_LIT', '",\n        awslogs-region        = "') at line 244, column 72.
  Expected one of: 
  	* SLASH
  	* QMARK
  	* __ANON_7
  	* __ANON_4
  	* __ANON_8
  	* COMMA
  	* __ANON_2
  	* __ANON_1
  	* RBRACE
  	* __ANON_9
  	* LSQB
  	* PERCENT
  	* __ANON_0
  	* STAR
  	* LESSTHAN
  	* __ANON_5
  	* PLUS
  	* __ANON_13
  	* MORETHAN
  	* __ANON_14
  	* DOT
  	* __ANON_6
  	* MINUS
  
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.9/dist-packages/terraform/hcl.py", line 61, in <module>
      try_load(Path(sys.argv[1]))
    File "/usr/local/lib/python3.9/dist-packages/terraform/hcl.py", line 18, in try_load
      debug(e)
    File "/usr/local/lib/python3.9/dist-packages/github_actions/debug.py", line 9, in debug
      for line in msg.splitlines():
  AttributeError: 'UnexpectedToken' object has no attribute 'splitlines'
  Detected s3 backend
Initializing Terraform
  
  Initializing the backend...
  
  Successfully configured the backend "s3"! Terraform will automatically
  use this backend unless the backend configuration changes.
  
  Initializing provider plugins...
  - Finding hashicorp/tls versions matching "~> 4.0.4"...
  - Finding hashicorp/random versions matching "~> 3.5"...
  - Finding hashicorp/aws versions matching "~> 4.63"...
  - Installing hashicorp/tls v4.0.4...
  - Installed hashicorp/tls v4.0.4 (signed by HashiCorp)
  - Installing hashicorp/random v3.5.1...
  - Installed hashicorp/random v3.5.1 (signed by HashiCorp)
  - Installing hashicorp/aws v4.65.0...
  - Installed hashicorp/aws v4.65.0 (signed by HashiCorp)
  
  Terraform has created a lock file .terraform.lock.hcl to record the provider
  selections it made above. Include this file in your version control repository
  so that Terraform can guarantee to make the same selections by default when
  you run "terraform init" in the future.
  
  Terraform has been successfully initialized!
Error: Failed to list workspaces
```

**Comment by dflook** [comment]
What version of terraform are you using, and what backend?

What does the relevant terraform code with the line 'awslogs-region' look like? Has that file changed since it last worked?

**Comment by jstuessy** [comment]
Terraform version 1.4.4.

that line didn't change, however the one above it did due to recommendations from TFLint

It used to be 

  container_definitions = jsonencode([{
    name      = "edge"
    image     = "5xxxxx.${var.edge_image_tag}"
    essential = true
    logConfiguration = {
      logDriver = "awslogs"
      options = {
        awslogs-group         = "${aws_cloudwatch_log_group.log_group.name}",
        awslogs-region        = "us-west-2",
        awslogs-stream-prefix = "ecs"
      }

It now shows
  container_definitions = jsonencode([{
    name      = "edge"
    image     = "5xxxx.{var.edge_image_tag}"
    essential = true
    logConfiguration = {
      logDriver = "awslogs"
      options = {
        awslogs-group         = aws_cloudwatch_log_group.log_group.name,
        awslogs-region        = "us-west-2",
        awslogs-stream-prefix = "ecs"
      }

**Comment by jstuessy** [comment]
However these changes were also setup in our production terraform files and they are able to apply and plan without issue. The only action that's having issues is the "New-workspace" job.

**Comment by jstuessy** [comment]
Figued out there was an interpolation issue.
