### ISSUE TITLE
Cannot run plan with S3 backend

### ISSUE THREAD

**Issue by Anton-Shutik** [dflook/terraform-github-actions#282]
### Problem description

Having issues when running tf plan on s3 backend.

My backend config looks like this:

```terraform
terraform {
  backend "s3" {
    bucket         = "terraform-state"
    key            = "aws/accounts/staging/vpcs/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "terraform-lock-table"
  }
}
```
It works fine from local machine, but does not work in GHA. What I'm doing wrong ?

### Terraform version

Terraform v1.3.9 on darwin_arm64

### Backend

s3

### Workflow YAML

```yaml
jobs:
    plan:
    runs-on: ubuntu-latest
    needs: [find-workloads]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        workload: ${{ fromJSON(needs.find-workloads.outputs.workloads_matrix) }}
      fail-fast: true
      max-parallel: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: "./${{ matrix.workload }}"
          var_file: "./${{ matrix.workload }}/config.tfvars.json"
          backend_config_file: "./${{ matrix.workload }}/backend.tf"
```

### Workflow log

```shell
Run dflook/terraform-plan@v1
  with:
    path: ./terraform/aws/accounts/staging/vpcs
    var_file: ./terraform/aws/accounts/staging/vpcs/config.tfvars.json
    add_github_comment: false
    backend_config_file: ./terraform/aws/accounts/staging/vpcs/backend.tf
    workspace: default
    parallelism: 0
    destroy: false
  env:
    GITHUB_TOKEN: ***
    AWS_DEFAULT_REGION: us-east-1
    AWS_REGION: us-east-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
/usr/bin/docker run --name danielflookterraformgithubactionssha[2](https://github.com/groveco/grove-infra/actions/runs/5622778355/job/15236067739#step:6:2)56c2bf25f288f2aace8f1987dd8f54b0559d[3](https://github.com/groveco/grove-infra/actions/runs/5622778355/job/15236067739#step:6:3)c33fe1520f19e861cd786a758d70f_e62c00 --label c9a[4](https://github.com/groveco/grove-infra/actions/runs/5622778355/job/15236067739#step:6:4)a[5](https://github.com/groveco/grove-infra/actions/runs/5622778355/job/15236067739#step:6:5) --workdir /github/workspace --rm -e "GITHUB_TOKEN" -e "AWS_DEFAULT_REGION" -e "AWS_REGION" -e "AWS_ACCESS_KEY_ID" -e "AWS_SECRET_ACCESS_KEY" -e "AWS_SESSION_TOKEN" -e "INPUT_PATH" -e "INPUT_VAR_FILE" -e "INPUT_ADD_GITHUB_COMMENT" -e "INPUT_BACKEND_CONFIG_FILE" -e "INPUT_WORKSPACE" -e "INPUT_BACKEND_CONFIG" -e "INPUT_VARIABLES" -e "INPUT_VAR" -e "INPUT_PARALLELISM" -e "INPUT_TARGET" -e "INPUT_REPLACE" -e "INPUT_DESTROY" -e "INPUT_LABEL" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e GITHUB_ACTIONS=true -e CI=true --entrypoint "/entrypoints/plan.sh" -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/grove-infra/grove-infra":"/github/workspace" danielflook/terraform-github-actions@sha25[6](https://github.com/groveco/grove-infra/actions/runs/5622778355/job/15236067739#step:6:6):c2bf25f288f2aace8f198[7](https://github.com/groveco/grove-infra/actions/runs/5622778355/job/15236067739#step:6:7)dd[8](https://github.com/groveco/grove-infra/actions/runs/5622778355/job/15236067739#step:6:8)f54b055[9](https://github.com/groveco/grove-infra/actions/runs/5622778355/job/15236067739#step:6:9)d3c33fe1520f19e861cd786a758d70f
Installing Terraform
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line [12](https://github.com/groveco/grove-infra/actions/runs/5622778355/job/15236067739#step:6:12)6, in feed_token
      action, arg = states[state][token.type]
  KeyError: '__ANON_3'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/dist-packages/terraform/hcl.py", line 16, in try_load
      return hcl2.load(f)
    File "/usr/local/lib/python3.9/dist-packages/hcl2/api.py", line 14, in load
      return loads(file.read(), with_meta=with_meta)
    File "/usr/local/lib/python3.9/dist-packages/hcl2/api.py", line 27, in loads
      tree = hcl2.parse(text + "\n")
    File "/usr/local/lib/python3.9/dist-packages/lark/lark.py", line 645, in parse
      return self.parser.parse(text, start=start, on_error=on_error)
    File "/usr/local/lib/python3.9/dist-packages/lark/parser_frontends.py", line 96, in parse
      return self.parser.parse(stream, chosen_start, **kw)
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 41, in parse
      return self.parser.parse(lexer, start)
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 171, in parse
      return self.parse_from_state(parser_state)
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 193, in parse_from_state
      raise e
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 184, in parse_from_state
      state.feed_token(token)
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 129, in feed_token
      raise UnexpectedToken(token, expected, state=self, interactive_parser=None)
  lark.exceptions.UnexpectedToken: Unexpected token Token('__ANON_3', 'security_groups') at line 5, column 7.
  Expected one of: 
  	* RBRACE
  	* __ANON_2
  	* SLASH
  	* MINUS
  	* __ANON_9
  	* QMARK
  	* PLUS
  	* __ANON_4
  	* STAR
  	* PERCENT
  	* COMMA
  	* __ANON_5
  	* __ANON_1
  	* __ANON_0
  	* LESSTHAN
  	* __ANON_8
  	* __ANON_6
  	* __ANON_7
  	* MORETHAN
  
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.9/dist-packages/terraform/hcl.py", line 61, in <module>
      try_load(Path(sys.argv[1]))
    File "/usr/local/lib/python3.9/dist-packages/terraform/hcl.py", line 18, in try_load
      debug(e)
    File "/usr/local/lib/python3.9/dist-packages/github_actions/debug.py", line 9, in debug
      for line in msg.splitlines():
  AttributeError: 'UnexpectedToken' object has no attribute 'splitlines'
  gpg: Signature made Mon Mar 20 18:12:41 2023 UTC
  gpg:                using RSA key 374EC75B4859[13](https://github.com/groveco/grove-infra/actions/runs/5622778355/job/15236067739#step:6:13)604A831CC7C820C6D5CD27AB87
  gpg: Good signature from "HashiCorp Security (hashicorp.com/security) <security@hashicorp.com>" [ultimate]
  terraform_1.3.9_linux_amd64.zip: OK
  Using latest terraform version that matches the required_version constraints
  Switched to Terraform v1.3.9
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 126, in feed_token
      action, arg = states[state][token.type]
  KeyError: '__ANON_3'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/dist-packages/terraform/hcl.py", line 16, in try_load
      return hcl2.load(f)
    File "/usr/local/lib/python3.9/dist-packages/hcl2/api.py", line [14](https://github.com/groveco/grove-infra/actions/runs/5622778355/job/15236067739#step:6:14), in load
      return loads(file.read(), with_meta=with_meta)
    File "/usr/local/lib/python3.9/dist-packages/hcl2/api.py", line 27, in loads
      tree = hcl2.parse(text + "\n")
    File "/usr/local/lib/python3.9/dist-packages/lark/lark.py", line 645, in parse
      return self.parser.parse(text, start=start, on_error=on_error)
    File "/usr/local/lib/python3.9/dist-packages/lark/parser_frontends.py", line 96, in parse
      return self.parser.parse(stream, chosen_start, **kw)
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 41, in parse
      return self.parser.parse(lexer, start)
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line [17](https://github.com/groveco/grove-infra/actions/runs/5622778355/job/15236067739#step:6:18)1, in parse
      return self.parse_from_state(parser_state)
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 193, in parse_from_state
      raise e
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line [18](https://github.com/groveco/grove-infra/actions/runs/5622778355/job/15236067739#step:6:19)4, in parse_from_state
      state.feed_token(token)
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 129, in feed_token
      raise UnexpectedToken(token, expected, state=self, interactive_parser=None)
  lark.exceptions.UnexpectedToken: Unexpected token Token('__ANON_3', 'security_groups') at line 5, column 7.
  Expected one of: 
  	* LESSTHAN
  	* MINUS
  	* __ANON_2
  	* QMARK
  	* COMMA
  	* MORETHAN
  	* PLUS
  	* __ANON_6
  	* PERCENT
  	* RBRACE
  	* __ANON_4
  	* __ANON_1
  	* __ANON_0
  	* SLASH
  	* __ANON_5
  	* STAR
  	* __ANON_8
  	* __ANON_7
  	* __ANON_9
  
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/lib/python3.9/runpy.py", line [19](https://github.com/groveco/grove-infra/actions/runs/5622778355/job/15236067739#step:6:20)7, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.9/dist-packages/terraform/hcl.py", line [61](https://github.com/groveco/grove-infra/actions/runs/5622778355/job/15236067739#step:6:62), in <module>
      try_load(Path(sys.argv[1]))
    File "/usr/local/lib/python3.9/dist-packages/terraform/hcl.py", line 18, in try_load
      debug(e)
    File "/usr/local/lib/python3.9/dist-packages/github_actions/debug.py", line 9, in debug
      for line in msg.splitlines():
  AttributeError: 'UnexpectedToken' object has no attribute 'splitlines'
  Detected s3 backend
Initializing Terraform
  Initializing modules...
  - east1 in ../../../../modules/aws/vpc
  - east2 in ../../../../modules/aws/vpc
  
  Initializing the backend...
  ╷
  │ Error: Unsupported block type
  │ 
  │   on backend.tf line 1:
  │    1: terraform {
  │ 
  │ Blocks of type "terraform" are not expected here.
  ╵
```

**Comment by dflook** [comment]
The `backend_config_file` input should point to a file that contains variables to complete a partial backend config block - not the backend block itself. It would be passed using `-backend-config` when running locally. See [Partial Configuration](https://developer.hashicorp.com/terraform/language/settings/backends/configuration#partial-configuration).

`backend.tf` in this case just needs to be in the location specified by `path`, which it looks like it is. You should be able to just not set `backend_config_file`.

**Comment by Anton-Shutik** [comment]
Phew, it just worked! Thanks!

Should I care about these error in the logs?

```
Traceback (most recent call last):
    File "/usr/local/lib/python3.9/dist-packages/terraform/hcl.py", line 16, in try_load
      return hcl2.load(f)
    File "/usr/local/lib/python3.9/dist-packages/hcl2/api.py", line 14, in load
      return loads(file.read(), with_meta=with_meta)
    File "/usr/local/lib/python3.9/dist-packages/hcl2/api.py", line [27](https://github.com/groveco/grove-infra/actions/runs/5623059083/job/15236939818#step:5:28), in loads
      tree = hcl2.parse(text + "\n")
    File "/usr/local/lib/python3.9/dist-packages/lark/lark.py", line 645, in parse
      return self.parser.parse(text, start=start, on_error=on_error)
    File "/usr/local/lib/python3.9/dist-packages/lark/parser_frontends.py", line 96, in parse
      return self.parser.parse(stream, chosen_start, **kw)
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 41, in parse
      return self.parser.parse(lexer, start)
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 171, in parse
      return self.parse_from_state(parser_state)
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 193, in parse_from_state
      raise e
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 184, in parse_from_state
      state.feed_token(token)
    File "/usr/local/lib/python3.9/dist-packages/lark/parsers/lalr_parser.py", line 1[29](https://github.com/groveco/grove-infra/actions/runs/5623059083/job/15236939818#step:5:30), in feed_token
      raise UnexpectedToken(token, expected, state=self, interactive_parser=None)
  lark.exceptions.UnexpectedToken: Unexpected token Token('__ANON_3', 'security_groups') at line 5, column 7.
  Expected one of: 
  	* __ANON_7
  	* __ANON_9
  	* QMARK
  	* __ANON_1
  	* SLASH
  	* __ANON_5
  	* LESSTHAN
  	* COMMA
  	* __ANON_2
  	* MINUS
  	* __ANON_4
  	* __ANON_6
  	* MORETHAN
  	* PLUS
  	* __ANON_0
  	* STAR
  	* __ANON_8
  	* RBRACE
  	* PERCENT
```

**Comment by dflook** [comment]
The hcl parser the actions use is not very good 😬 
Can you tell what file it is having trouble with? It will have security_groups on or near line 5, column 7.
It would be helpful is you could post a snippet of it.

The actions only need to parse the terraform to get the backend config. Since this is working now, you can ignore the errors.

**Comment by Anton-Shutik** [comment]
It looks like this:

```terraform
locals {
  vpc_config = var.import == true ? {} : {
    east1 = {
      subnets         = length(keys(var.vpcs.east1)) > 0 ? module.east1[0].subnet_ids : {}
      security_groups = length(keys(var.vpcs.east1)) > 0 ? module.east1[0].sg_ids : {}
    }
    east2 = {
      subnets         = length(keys(var.vpcs.east2)) > 0 ? module.east2[0].subnet_ids : {}
      security_groups = length(keys(var.vpcs.east2)) > 0 ? module.east2[0].sg_ids : {}
    }
  }
}
```
